version: '3.8'

services:
  building-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    environment:
      - WORKERS=1
      - PORT=5001
      - TIMEOUT=60
      - MAX_REQUESTS=500
      - BACKEND_TYPE=DATALAKE  # DATALAKE or BLOBSTORAGE
      - AZURE_TENANT_ID
      - AZURE_NAME
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - WEIGHTS_LOCATION=cooked/vectorisation/model_weights/building.h5

  line-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    environment:
      - WORKERS=1
      - PORT=5002
      - TIMEOUT=60
      - MAX_REQUESTS=500
      - BACKEND_TYPE=DATALAKE  # DATALAKE or BLOBSTORAGE
      - AZURE_TENANT_ID
      - AZURE_NAME
      - AZURE_CLIENT_ID
      - AZURE_CLIENT_SECRET
      - WEIGHTS_LOCATION=cooked/vectorisation/model_weights/line.h5
