apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: building
  name: building
spec:
  replicas: 1
  selector:
    matchLabels:
      app: building
  template:
    metadata:
      labels:
        app: building
    spec:
      containers:
      - name: building
        image: bsegmentation:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
              name: building-conf
          - secretRef:
              name: azure-storage
