apiVersion: v1
kind: Service
metadata:
  labels:
    app: building
  name: building-service
spec:
  type: NodePort
  ports:
  - name: "flask"
    port: 5000
    targetPort: 5000
  selector:
    app: building
